# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb7735f82478cb983840f79b4ed9bc3530d8511ce9cacebab8639458ef79566d94a8b356c31839d2f35128e4d72f4ca5f0ac483197209de140c19faf555ea581

test:
  secret_key_base: 4ea520b2c44833007b2817ac1e594a3decd06b4c78de1d3604195adc28a3cd56d81488e4b40ac247e39553a2d9e38831f002eeede754d6075fb761db6bf668f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
